import turtle
turtle.up()
turtle.shape('turtle')
turtle.goto(-80, 0)
turtle.color('blue')
turtle.down()
turtle.begin_fill()
turtle.forward(300)
turtle.left(120)
turtle.forward(300)
turtle.left(60)
turtle.forward(300)
turtle.left(60)
turtle.forward(300)
turtle.left(60)
turtle.forward(300)
turtle.left(60)
turtle.forward(300)
turtle.left(60)
turtle.forward(300)
turtle.end_fill()
turtle.hideturtle()
turtle.done()